image: cyang019/cpphpc:latest

stages:
  - build
  - test

build_job:
  stage: build
  artifacts:
    untracked: true
  script:
    - git submodule update --recursive --init
    - mkdir build
    - cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
    - ninja

test_job:
  stage: test
  dependencies:
    - build_job
  script:
    - cd /builds/chen.yang/dnpsoup/build
    - ./tests/test_dnpsoup_core
