# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:latest

prepare:
  stage: install dependencies
  script:
    - apt-get update
    - ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install -y tzdata
    - dpkg-reconfigure --frontend noninteractive tzdata
    - apt-get install -y g++ git cmake ninja-build libopenblas-dev liblapack-dev liblapacke-dev libpthread-stubs0-dev gfortran

build:
  stage: build
  script:
    - git submodule update --recursive --init
    - mkdir build
    - cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
    - ninja

test:
  stage: test
  script:
    - ./tests/test_dnpsoup_core

