# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.5

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - git submodule update --recursive --init
          - apt-get update
          - apt-get install -y cmake ninja-build libopenblas-dev liblapack-dev libpthread-stubs0-dev
          - mkdir build
          - cd build
          - cmake .. -GNinja
          - ninja
          - ./tests/test_dnpsoup_core
