version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_and_test:
    docker:
      - image: cyang019/cpphpc:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:09:70:bc:a2:be:3d:5f:48:d9:bc:7d:5d:c8:ee:21"
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - run: cmake --build build
      - run: ./build/tests/test_dnpsoup_core 

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_and_test
