version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cyang019/cpphpc:latest
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: cmake -GNinja -DCMAKE_BUILD_TYPE=Release -B build && cmake --build build
  test:
    docker:
      - image: cyang019/cpphpc:latest
    steps:
      - checkout
      - run: ./build/tests/test_dnpsoup_core 

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
